/**
 * Site-specific demo content — generated by SiteAssembler
 * Site: Degrau da Bola
 * DO NOT EDIT MANUALLY
 */

export interface Category {
  id: string;
  name: string;
  slug: string;
  description?: string;
}

export interface Article {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  category: string;
  categorySlug: string;
  author: string;
  publishedAt: string;
  imageUrl?: string;
  isVideo?: boolean;
  readCount?: number;
  featured?: boolean;
  keyPoints?: string[];
}

export interface BreakingHeadline {
  id: string;
  text: string;
  slug?: string;
  urgent?: boolean;
}

export interface AlertItem {
  id: string;
  level: string;
  title: string;
  href?: string;
  publishedAt: string;
}

export interface LiveUpdate {
  id: string;
  at: string;
  source: string;
  text: string;
}

export interface LiveStory {
  id: string;
  slug: string;
  title: string;
  summary: string;
  updatedAt: string;
  updates: LiveUpdate[];
}

export const categories: Category[] = [
  {
    "id": "cat-serie-b",
    "name": "Série B",
    "slug": "serie-b",
    "description": "Cobertura de Série B em Degrau da Bola"
  },
  {
    "id": "cat-promotion-race",
    "name": "promotion race",
    "slug": "promotion-race",
    "description": "Cobertura de promotion race em Degrau da Bola"
  },
  {
    "id": "cat-club-news",
    "name": "club news",
    "slug": "club-news",
    "description": "Cobertura de club news em Degrau da Bola"
  },
  {
    "id": "cat-regional-news",
    "name": "regional news",
    "slug": "regional-news",
    "description": "Cobertura de regional news em Degrau da Bola"
  },
  {
    "id": "cat-fixtures",
    "name": "fixtures",
    "slug": "fixtures",
    "description": "Cobertura de fixtures em Degrau da Bola"
  },
  {
    "id": "cat-results",
    "name": "results",
    "slug": "results",
    "description": "Cobertura de results em Degrau da Bola"
  }
];

export const breakingHeadlines: BreakingHeadline[] = [
  {
    "id": "brk-1",
    "text": "AO VIVO — Série B: atualização urgente para leitores de Degrau da Bola",
    "slug": "serie-b-em-foco-tres-leituras-que-importam-hoje-6m7",
    "urgent": true
  },
  {
    "id": "brk-2",
    "text": "AO VIVO — promotion race: atualização urgente para leitores de Degrau da Bola",
    "slug": "por-que-serie-b-domina-a-conversa-e-o-que-vem-a-seguir-6m8",
    "urgent": false
  },
  {
    "id": "brk-3",
    "text": "AO VIVO — club news: atualização urgente para leitores de Degrau da Bola",
    "slug": "egrau-da-bola-explica-o-ponto-chave-de-serie-b-nesta-semana-6m9",
    "urgent": false
  }
];

export const articles: Article[] = [
  {
    "id": "art-1",
    "slug": "serie-b-em-foco-tres-leituras-que-importam-hoje-6m7",
    "title": "Série B em foco: três leituras que importam hoje",
    "excerpt": "Cobertura rápida e objetiva sobre Série B, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Degrau da Bola</strong> na seção <em>Série B</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Série B",
    "categorySlug": "serie-b",
    "author": "Hugo Almeida",
    "publishedAt": "2026-09-27T13:56:50.633Z",
    "imageUrl": "https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=800&q=80",
    "readCount": 5775,
    "featured": true,
    "isVideo": true
  },
  {
    "id": "art-2",
    "slug": "por-que-serie-b-domina-a-conversa-e-o-que-vem-a-seguir-6m8",
    "title": "Por que Série B domina a conversa — e o que vem a seguir",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Degrau da Bola</strong> na seção <em>Série B</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Série B",
    "categorySlug": "serie-b",
    "author": "Ana Ribeiro",
    "publishedAt": "2026-09-27T06:56:50.633Z",
    "imageUrl": "https://images.unsplash.com/photo-1574629810360-7abcae5a4a2a?w=800&q=80",
    "readCount": 6772,
    "featured": true,
    "isVideo": false
  },
  {
    "id": "art-3",
    "slug": "egrau-da-bola-explica-o-ponto-chave-de-serie-b-nesta-semana-6m9",
    "title": "Degrau da Bola explica: o ponto-chave de Série B nesta semana",
    "excerpt": "Leitura direta para quem acompanha Série B no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Degrau da Bola</strong> na seção <em>Série B</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "Série B",
    "categorySlug": "serie-b",
    "author": "Bruno Costa",
    "publishedAt": "2026-09-26T23:56:50.633Z",
    "imageUrl": "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&q=80",
    "readCount": 7769,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-4",
    "slug": "promotion-race-o-que-muda-agora-e-o-impacto-direto-para-o-publico-de-egr-6ma",
    "title": "promotion race: o que muda agora e o impacto direto para o público de Degrau da Bola",
    "excerpt": "Cobertura rápida e objetiva sobre promotion race, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Degrau da Bola</strong> na seção <em>promotion race</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "promotion race",
    "categorySlug": "promotion-race",
    "author": "Camila Souza",
    "publishedAt": "2026-09-26T16:56:50.633Z",
    "imageUrl": "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80",
    "readCount": 8766,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-5",
    "slug": "bastidores-de-promotion-race-analise-com-numeros-e-contexto-6mb",
    "title": "Bastidores de promotion race — análise com números e contexto",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Degrau da Bola</strong> na seção <em>promotion race</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "promotion race",
    "categorySlug": "promotion-race",
    "author": "Diego Martins",
    "publishedAt": "2026-09-26T09:56:50.633Z",
    "imageUrl": "https://images.unsplash.com/photo-1461896836934-ffe607ba6851?w=800&q=80",
    "readCount": 9763,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-6",
    "slug": "ultima-hora-em-promotion-race-decisoes-que-mexem-com-a-rodada-6mc",
    "title": "Última hora em promotion race: decisões que mexem com a rodada",
    "excerpt": "Leitura direta para quem acompanha promotion race no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Degrau da Bola</strong> na seção <em>promotion race</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "promotion race",
    "categorySlug": "promotion-race",
    "author": "Elena Prado",
    "publishedAt": "2026-09-29T02:56:50.633Z",
    "imageUrl": "https://images.unsplash.com/photo-1486286701208-1d58e9338013?w=800&q=80",
    "readCount": 10760,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-7",
    "slug": "club-news-em-foco-tres-leituras-que-importam-hoje-6md",
    "title": "club news em foco: três leituras que importam hoje",
    "excerpt": "Cobertura rápida e objetiva sobre club news, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Degrau da Bola</strong> na seção <em>club news</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "club news",
    "categorySlug": "club-news",
    "author": "Felipe Nunes",
    "publishedAt": "2026-09-28T19:56:50.633Z",
    "imageUrl": "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80",
    "readCount": 11757,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-8",
    "slug": "por-que-club-news-domina-a-conversa-e-o-que-vem-a-seguir-6me",
    "title": "Por que club news domina a conversa — e o que vem a seguir",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Degrau da Bola</strong> na seção <em>club news</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "club news",
    "categorySlug": "club-news",
    "author": "Gabriela Lopes",
    "publishedAt": "2026-09-28T12:56:50.633Z",
    "imageUrl": "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&q=80",
    "readCount": 12754,
    "featured": false,
    "isVideo": true
  },
  {
    "id": "art-9",
    "slug": "egrau-da-bola-explica-o-ponto-chave-de-club-news-nesta-semana-6mf",
    "title": "Degrau da Bola explica: o ponto-chave de club news nesta semana",
    "excerpt": "Leitura direta para quem acompanha club news no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Degrau da Bola</strong> na seção <em>club news</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "club news",
    "categorySlug": "club-news",
    "author": "Hugo Almeida",
    "publishedAt": "2026-09-28T05:56:50.633Z",
    "imageUrl": "https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=800&q=80",
    "readCount": 13751,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-10",
    "slug": "regional-news-o-que-muda-agora-e-o-impacto-direto-para-o-publico-de-egra-6mg",
    "title": "regional news: o que muda agora e o impacto direto para o público de Degrau da Bola",
    "excerpt": "Cobertura rápida e objetiva sobre regional news, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Degrau da Bola</strong> na seção <em>regional news</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "regional news",
    "categorySlug": "regional-news",
    "author": "Ana Ribeiro",
    "publishedAt": "2026-09-27T22:56:50.633Z",
    "imageUrl": "https://images.unsplash.com/photo-1574629810360-7abcae5a4a2a?w=800&q=80",
    "readCount": 14748,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-11",
    "slug": "bastidores-de-regional-news-analise-com-numeros-e-contexto-6mh",
    "title": "Bastidores de regional news — análise com números e contexto",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Degrau da Bola</strong> na seção <em>regional news</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "regional news",
    "categorySlug": "regional-news",
    "author": "Bruno Costa",
    "publishedAt": "2026-09-27T15:56:50.633Z",
    "imageUrl": "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&q=80",
    "readCount": 15745,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-12",
    "slug": "ultima-hora-em-regional-news-decisoes-que-mexem-com-a-rodada-6mi",
    "title": "Última hora em regional news: decisões que mexem com a rodada",
    "excerpt": "Leitura direta para quem acompanha regional news no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Degrau da Bola</strong> na seção <em>regional news</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "regional news",
    "categorySlug": "regional-news",
    "author": "Camila Souza",
    "publishedAt": "2026-09-27T08:56:50.633Z",
    "imageUrl": "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80",
    "readCount": 16742,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-13",
    "slug": "fixtures-em-foco-tres-leituras-que-importam-hoje-6mj",
    "title": "fixtures em foco: três leituras que importam hoje",
    "excerpt": "Cobertura rápida e objetiva sobre fixtures, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Degrau da Bola</strong> na seção <em>fixtures</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "fixtures",
    "categorySlug": "fixtures",
    "author": "Diego Martins",
    "publishedAt": "2026-09-27T01:56:50.633Z",
    "imageUrl": "https://images.unsplash.com/photo-1461896836934-ffe607ba6851?w=800&q=80",
    "readCount": 17739,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-14",
    "slug": "por-que-fixtures-domina-a-conversa-e-o-que-vem-a-seguir-6mk",
    "title": "Por que fixtures domina a conversa — e o que vem a seguir",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Degrau da Bola</strong> na seção <em>fixtures</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "fixtures",
    "categorySlug": "fixtures",
    "author": "Elena Prado",
    "publishedAt": "2026-09-26T18:56:50.633Z",
    "imageUrl": "https://images.unsplash.com/photo-1486286701208-1d58e9338013?w=800&q=80",
    "readCount": 18736,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-15",
    "slug": "egrau-da-bola-explica-o-ponto-chave-de-fixtures-nesta-semana-6ml",
    "title": "Degrau da Bola explica: o ponto-chave de fixtures nesta semana",
    "excerpt": "Leitura direta para quem acompanha fixtures no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Degrau da Bola</strong> na seção <em>fixtures</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "fixtures",
    "categorySlug": "fixtures",
    "author": "Felipe Nunes",
    "publishedAt": "2026-09-26T11:56:50.634Z",
    "imageUrl": "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80",
    "readCount": 19733,
    "featured": false,
    "isVideo": true
  },
  {
    "id": "art-16",
    "slug": "results-o-que-muda-agora-e-o-impacto-direto-para-o-publico-de-egrau-da-b-6mm",
    "title": "results: o que muda agora e o impacto direto para o público de Degrau da Bola",
    "excerpt": "Cobertura rápida e objetiva sobre results, com contexto e próximos capítulos.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Degrau da Bola</strong> na seção <em>results</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "results",
    "categorySlug": "results",
    "author": "Gabriela Lopes",
    "publishedAt": "2026-09-29T04:56:50.634Z",
    "imageUrl": "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&q=80",
    "readCount": 20730,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-17",
    "slug": "bastidores-de-results-analise-com-numeros-e-contexto-6mn",
    "title": "Bastidores de results — análise com números e contexto",
    "excerpt": "O que já está confirmado, o que ainda é especulação e o que acompanhar nas próximas horas.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Degrau da Bola</strong> na seção <em>results</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "results",
    "categorySlug": "results",
    "author": "Hugo Almeida",
    "publishedAt": "2026-09-28T21:56:50.634Z",
    "imageUrl": "https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=800&q=80",
    "readCount": 21727,
    "featured": false,
    "isVideo": false
  },
  {
    "id": "art-18",
    "slug": "ultima-hora-em-results-decisoes-que-mexem-com-a-rodada-6mo",
    "title": "Última hora em results: decisões que mexem com a rodada",
    "excerpt": "Leitura direta para quem acompanha results no celular — sem enrolação.",
    "content": "<p>Esta é uma matéria demonstrativa de <strong>Degrau da Bola</strong> na seção <em>results</em>. O texto simula cobertura jornalística em pt-BR para validar layout, tipografia e hierarquia.</p><p>Em produção, o conteúdo virá do CMS. Aqui o objetivo é deixar cada portal com seed editorial próprio — categorias, títulos e destaques alinhados à identidade do site.</p>",
    "category": "results",
    "categorySlug": "results",
    "author": "Ana Ribeiro",
    "publishedAt": "2026-09-28T14:56:50.634Z",
    "imageUrl": "https://images.unsplash.com/photo-1574629810360-7abcae5a4a2a?w=800&q=80",
    "readCount": 22724,
    "featured": false,
    "isVideo": false
  }
];

export const alerts: AlertItem[] = [
  {
    "id": "alert-1",
    "level": "Urgente",
    "title": "Atualização crítica em Série B — acompanhe minuto a minuto",
    "href": "/artigo/serie-b-em-foco-tres-leituras-que-importam-hoje-6m7",
    "publishedAt": "2026-09-27T13:56:50.634Z"
  },
  {
    "id": "alert-2",
    "level": "Importante",
    "title": "Degrau da Bola: comunicado oficial sobre cobertura em tempo real",
    "href": "/alertas",
    "publishedAt": "2026-09-27T06:56:50.634Z"
  },
  {
    "id": "alert-3",
    "level": "Aviso",
    "title": "Manutenção programada da área de alertas (demo)",
    "publishedAt": "2026-09-26T23:56:50.634Z"
  },
  {
    "id": "alert-4",
    "level": "Urgente",
    "title": "Desenvolvimento em promotion race com impacto nacional",
    "href": "/artigo/por-que-serie-b-domina-a-conversa-e-o-que-vem-a-seguir-6m8",
    "publishedAt": "2026-09-26T16:56:50.634Z"
  },
  {
    "id": "alert-5",
    "level": "Importante",
    "title": "Fontes oficiais confirmam novo capítulo da história em acompanhamento",
    "publishedAt": "2026-09-26T09:56:50.634Z"
  },
  {
    "id": "alert-6",
    "level": "Aviso",
    "title": "Lembrete editorial: confira a política de atualização ao vivo",
    "href": "/sobre",
    "publishedAt": "2026-09-29T02:56:50.634Z"
  }
];

export const liveStories: LiveStory[] = [
  {
    "id": "live-1",
    "slug": "demo-nacional",
    "title": "AO VIVO — Cobertura nacional de Degrau da Bola",
    "summary": "Linha do tempo demonstrativa com fontes rotuladas e âncoras estáveis.",
    "updatedAt": "2026-09-27T13:56:50.634Z",
    "updates": [
      {
        "id": "upd-1",
        "at": "2026-09-27T13:56:50.634Z",
        "source": "Redação",
        "text": "Início da cobertura ao vivo. Equipe monitora fontes oficiais e correspondentes."
      },
      {
        "id": "upd-2",
        "at": "2026-09-27T06:56:50.634Z",
        "source": "Agência",
        "text": "Primeira confirmação independente chega à mesa. Texto em verificação cruzada."
      },
      {
        "id": "upd-3",
        "at": "2026-09-26T23:56:50.634Z",
        "source": "Correspondente",
        "text": "Cena local descrita com cautela — sem especulação além do observado."
      },
      {
        "id": "upd-4",
        "at": "2026-09-26T16:56:50.634Z",
        "source": "Redação",
        "text": "Linha do tempo reorganizada. Âncoras de atualização permanecem estáveis."
      },
      {
        "id": "upd-5",
        "at": "2026-09-26T09:56:50.634Z",
        "source": "Especialista",
        "text": "Contexto rápido para leitores que acabaram de entrar na cobertura."
      },
      {
        "id": "upd-6",
        "at": "2026-09-29T02:56:50.634Z",
        "source": "Redação",
        "text": "Última atualização desta demonstração. Em produção, o CMS alimenta este feed."
      }
    ]
  },
  {
    "id": "live-2",
    "slug": "demo-regional",
    "title": "AO VIVO — Frente regional (br-bahia)",
    "summary": "Segundo demo de live-blog para validar rotas e UI.",
    "updatedAt": "2026-09-26T23:56:50.634Z",
    "updates": [
      {
        "id": "upd-r1",
        "at": "2026-09-26T23:56:50.634Z",
        "source": "Redação regional",
        "text": "Abertura do blog regional com foco em impacto local."
      },
      {
        "id": "upd-r2",
        "at": "2026-09-26T16:56:50.634Z",
        "source": "Prefeitura / órgão local (demo)",
        "text": "Nota oficial demonstrativa — rotular fonte é obrigatório neste layout."
      }
    ]
  }
];
